(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports) module.exports=api;
  if(root){ root.HabitLogicStudy=api; if(root.document) api.init(); }
})(typeof window!=='undefined'?window:globalThis,function(){
  const REL={AO:'Contradictories',EI:'Contradictories',AE:'Contraries',IO:'Subcontraries',AI:'Subalternation',EO:'Subalternation'};
  function relationshipBetween(a,b){return REL[[a,b].sort().join('')]||'No direct square relationship';}
  function truthInference(from,truth,target){
    if(from===target)return truth;
    const rel=relationshipBetween(from,target);
    if(rel==='Contradictories')return truth==='True'?'False':'True';
    if(rel==='Contraries')return truth==='True'?'False':'Undetermined';
    if(rel==='Subcontraries')return truth==='False'?'True':'Undetermined';
    if(from==='A'&&target==='I')return truth==='True'?'True':'Undetermined';
    if(from==='E'&&target==='O')return truth==='True'?'True':'Undetermined';
    if(from==='I'&&target==='A')return truth==='False'?'False':'Undetermined';
    if(from==='O'&&target==='E')return truth==='False'?'False':'Undetermined';
    return 'Undetermined';
  }
  function classifyConditionalForm(p,q,premise2,conclusion){
    if(premise2===p&&conclusion===q)return 'Modus Ponens';
    if(premise2==='not '+q&&conclusion==='not '+p)return 'Modus Tollens';
    if(premise2===q&&conclusion===p)return 'Affirming the Consequent';
    if(premise2==='not '+p&&conclusion==='not '+q)return 'Denying the Antecedent';
    return 'Unknown';
  }
  const sqState={correct:0,incorrect:0,streak:0,missed:[],current:null,selected:null};
  const erState={correct:0,incorrect:0,streak:0,missed:[],current:null,selected:null};
  const terms=[['dogs','mammals'],['lawyers','professionals'],['birds','animals'],['students','readers'],['roses','flowers'],['cars','vehicles']];
  const rand=a=>a[Math.floor(Math.random()*a.length)];
  const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
  const prop=(t,s,p)=>t==='A'?`All ${s} are ${p}.`:t==='E'?`No ${s} are ${p}.`:t==='I'?`Some ${s} are ${p}.`:`Some ${s} are not ${p}.`;
  const tname=t=>({A:'Universal affirmative (A)',E:'Universal negative (E)',I:'Particular affirmative (I)',O:'Particular negative (O)'})[t];
  function squareQuestion(){
    const cats=[...document.querySelectorAll('#logicSquareCats input:checked')].map(x=>x.value); const cat=rand(cats.length?cats:['identify','relations','truth','translate']);
    const [s,p]=rand(terms), types=['A','E','I','O'];
    if(cat==='identify'){const t=rand(types);return {cat:'Identification',stem:`What type is: “${prop(t,s,p)}”`,choices:shuffle(types.map(tname)),answer:tname(t),why:`It has the ${t} form: ${prop(t,'S','P')}`};}
    if(cat==='relations'){const pair=rand([['A','O'],['E','I'],['A','E'],['I','O'],['A','I'],['E','O']]);return {cat:'Relationship',stem:`What is the relationship between ${pair[0]} and ${pair[1]}?`,choices:shuffle(['Contradictories','Contraries','Subcontraries','Subalternation']),answer:relationshipBetween(...pair),why:`${pair[0]} and ${pair[1]} are ${relationshipBetween(...pair).toLowerCase()} on the traditional square.`};}
    if(cat==='truth'){const a=rand(types),b=rand(types.filter(x=>x!==a)),tv=rand(['True','False']);return {cat:'Truth inference',stem:`If “${prop(a,s,p)}” is ${tv.toLowerCase()}, what must be true of “${prop(b,s,p)}”?`,choices:['True','False','Undetermined'],answer:truthInference(a,tv,b),why:`Use the ${relationshipBetween(a,b).toLowerCase()} relationship between ${a} and ${b}.`};}
    const t=rand(types);const ordinary={A:`Every ${s.slice(0,-1)||s} is one of the ${p}.`,E:`Not a single ${s.slice(0,-1)||s} is one of the ${p}.`,I:`At least one of the ${s} is one of the ${p}.`,O:`At least one of the ${s} is not one of the ${p}.`}[t];return {cat:'Translation',stem:`Which categorical form matches: “${ordinary}”`,choices:shuffle(types.map(x=>prop(x,s,p))),answer:prop(t,s,p),why:`That sentence translates to ${prop(t,s,p)}, the ${t} form.`};
  }
  function errorQuestion(){
    const cats=[...document.querySelectorAll('#logicErrorCats input:checked')].map(x=>x.value); const cat=rand(cats.length?cats:['mp','mt','ac','da','um','ilmj','ilmn','four']);
    const map={mp:['Modus Ponens','If P then Q. P. Therefore Q.','Valid','Affirms the antecedent and concludes the consequent.'],mt:['Modus Tollens','If P then Q. Not Q. Therefore not P.','Valid','Denies the consequent and validly denies the antecedent.'],ac:['Affirming the Consequent','If P then Q. Q. Therefore P.','Invalid','Affirming the consequent does not prove the antecedent.'],da:['Denying the Antecedent','If P then Q. Not P. Therefore not Q.','Invalid','Denying the antecedent does not rule out the consequent.'],um:['Undistributed Middle','All cats are animals. All dogs are animals. Therefore all dogs are cats.','Invalid','The middle term is never distributed.'],ilmj:['Illicit Major','All dogs are mammals. No cats are dogs. Therefore no cats are mammals.','Invalid','The major term is distributed in the conclusion but not the premise.'],ilmn:['Illicit Minor','All poets are writers. All poets are dreamers. Therefore all dreamers are writers.','Invalid','The minor term is distributed in the conclusion but not its premise.'],four:['Four-Term Fallacy','All banks keep money safe. River banks are banks. Therefore river banks keep money safe.','Invalid','“Bank” changes meaning, creating four terms.']};
    const [name,arg,valid,why]=map[cat]; const askName=Math.random()<.65;
    return askName?{cat:name,stem:`Identify the form or error:\n${arg}`,choices:shuffle(Object.values(map).map(v=>v[0]).slice(0,8)),answer:name,why}:{cat:name,stem:`Is this argument valid or invalid?\n${arg}`,choices:['Valid','Invalid'],answer:valid,why:`This is ${name}. ${why}`};
  }
  function cssEscape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function renderQuestion(kind,q){const pre=kind==='square'?'logicSquare':'logicError',state=kind==='square'?sqState:erState;state.current=q;state.selected=null;document.getElementById(pre+'Stem').innerHTML=cssEscape(q.stem).replace(/\n/g,'<br>');document.getElementById(pre+'Feedback').innerHTML='';const box=document.getElementById(pre+'Choices');box.innerHTML='';q.choices.forEach(c=>{const b=document.createElement('button');b.className='logicChoice';b.textContent=c;b.onclick=()=>{if(state.current!==q)return;[...box.children].forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.selected=c;};box.appendChild(b);});}
  function check(kind){const pre=kind==='square'?'logicSquare':'logicError',s=kind==='square'?sqState:erState;if(!s.current||!s.selected)return;const ok=s.selected===s.current.answer;if(ok){s.correct++;s.streak++;}else{s.incorrect++;s.streak=0;s.missed.push(s.current);}document.getElementById(pre+'Feedback').innerHTML=`<div class="${ok?'logicGood':'logicBad'}"><strong>${ok?'Correct':'Incorrect'}</strong></div><div><strong>Answer:</strong> ${cssEscape(s.current.answer)}</div><div>${cssEscape(s.current.why)}</div>`;updateStats(kind);}
  function updateStats(kind){const pre=kind==='square'?'logicSquare':'logicError',s=kind==='square'?sqState:erState,total=s.correct+s.incorrect,acc=total?Math.round(100*s.correct/total):0;document.getElementById(pre+'Stats').textContent=`Correct ${s.correct} • Incorrect ${s.incorrect} • ${acc}% • Streak ${s.streak}`;document.getElementById(pre+'Missed').textContent=`Missed to review: ${s.missed.length}`;}
  function review(kind){const s=kind==='square'?sqState:erState;if(!s.missed.length)return;renderQuestion(kind,rand(s.missed));}
  function logicMarkup(){return `<div class="logicHeader"><div><h2>Logic</h2><div class="sub">Practice categorical logic and common formal reasoning errors.</div></div><div class="logicModes"><button class="primary" data-logic-mode="square">Square of Opposition</button><button data-logic-mode="errors">Reasoning Errors</button></div></div><div id="logicModeSquare" class="logicMode"><div class="logicLayout"><section class="card"><h3>Study categories</h3><div id="logicSquareCats" class="logicChecks">${[['identify','A / E / I / O identification'],['relations','Contradictories, contraries, subcontraries, subalternation'],['truth','Truth-value inference'],['translate','Ordinary-language translation']].map(([v,l])=>`<label><input type="checkbox" value="${v}" checked> ${l}</label>`).join('')}</div><div class="logicActions"><button id="logicSquareNew" class="primary">New Question</button><button id="logicSquareCheck">Check Answer</button><button id="logicSquareReview">Review Missed</button></div></section><section class="card"><div id="logicSquareStem" class="logicStem">Tap New Question to begin.</div><div id="logicSquareChoices" class="logicChoiceGrid"></div><div id="logicSquareFeedback" class="logicFeedback"></div></section><aside class="card"><h3>Progress</h3><div id="logicSquareStats">Correct 0 • Incorrect 0 • 0% • Streak 0</div><div id="logicSquareMissed" class="small">Missed to review: 0</div><div class="logicSquareRef"><strong>A</strong> All S are P<br><strong>E</strong> No S are P<br><strong>I</strong> Some S are P<br><strong>O</strong> Some S are not P</div></aside></div></div><div id="logicModeErrors" class="logicMode hidden"><div class="logicLayout"><section class="card"><h3>Study categories</h3><div id="logicErrorCats" class="logicChecks">${[['mp','Modus Ponens'],['mt','Modus Tollens'],['ac','Affirming the Consequent'],['da','Denying the Antecedent'],['um','Undistributed Middle'],['ilmj','Illicit Major'],['ilmn','Illicit Minor'],['four','Four-Term Fallacy']].map(([v,l])=>`<label><input type="checkbox" value="${v}" checked> ${l}</label>`).join('')}</div><div class="logicActions"><button id="logicErrorNew" class="primary">New Question</button><button id="logicErrorCheck">Check Answer</button><button id="logicErrorReview">Review Missed</button></div></section><section class="card"><div id="logicErrorStem" class="logicStem">Tap New Question to begin.</div><div id="logicErrorChoices" class="logicChoiceGrid"></div><div id="logicErrorFeedback" class="logicFeedback"></div></section><aside class="card"><h3>Progress</h3><div id="logicErrorStats">Correct 0 • Incorrect 0 • 0% • Streak 0</div><div id="logicErrorMissed" class="small">Missed to review: 0</div><div class="logicSquareRef"><strong>MP</strong> If P→Q; P; ∴Q<br><strong>MT</strong> If P→Q; ¬Q; ∴¬P<br><strong>AC</strong> If P→Q; Q; ∴P<br><strong>DA</strong> If P→Q; ¬P; ∴¬Q</div></aside></div></div>`;}
  function addNavButton(){document.querySelectorAll('.globalNavBtn[data-tab="greatbooks"], .tab[data-tab="greatbooks"]').forEach(anchor=>{const parent=anchor.parentElement;if(parent.querySelector('[data-tab="logic"]'))return;const b=document.createElement(anchor.tagName==='BUTTON'?'button':'div');b.className=anchor.className;b.dataset.tab='logic';b.textContent='Logic';anchor.insertAdjacentElement('afterend',b);});}
  function showLogic(){document.querySelectorAll('[id^="tab-"]').forEach(x=>x.classList.add('hidden'));const sec=document.getElementById('tab-logic');if(sec)sec.classList.remove('hidden');const menu=document.getElementById('globalMenuPanel');if(menu)menu.style.display='none';}
  function bindNav(){document.addEventListener('click',e=>{const t=e.target.closest('[data-tab]');if(!t)return;if(t.dataset.tab==='logic'){e.preventDefault();e.stopImmediatePropagation();showLogic();}else{const sec=document.getElementById('tab-logic');if(sec)sec.classList.add('hidden');}},true);}
  function init(){if(!document.body||document.getElementById('tab-logic'))return;addNavButton();const ref=document.getElementById('tab-family')||document.querySelector('[id^="tab-"]:last-of-type');if(!ref)return;const sec=document.createElement('div');sec.id='tab-logic';sec.className='hidden';sec.innerHTML=logicMarkup();ref.parentElement.insertBefore(sec,ref);bindNav();sec.querySelectorAll('[data-logic-mode]').forEach(b=>b.onclick=()=>{sec.querySelectorAll('[data-logic-mode]').forEach(x=>x.classList.toggle('primary',x===b));document.getElementById('logicModeSquare').classList.toggle('hidden',b.dataset.logicMode!=='square');document.getElementById('logicModeErrors').classList.toggle('hidden',b.dataset.logicMode!=='errors');});document.getElementById('logicSquareNew').onclick=()=>renderQuestion('square',squareQuestion());document.getElementById('logicSquareCheck').onclick=()=>check('square');document.getElementById('logicSquareReview').onclick=()=>review('square');document.getElementById('logicErrorNew').onclick=()=>renderQuestion('errors',errorQuestion());document.getElementById('logicErrorCheck').onclick=()=>check('errors');document.getElementById('logicErrorReview').onclick=()=>review('errors');}
  return {init,showLogic,relationshipBetween,truthInference,classifyConditionalForm};
});